name: Continous Integration

on:
  push:
    branches:      
      - develop
      - release/*
      
jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow        

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    
    - name: Build
      run: dotnet build ./src/Solution.sln --configuration Release
    
    - name: Test
      run: dotnet test ./src/Solution.sln